name: Update Repo Slide

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install (no extraneous)
        working-directory: docs/r.svg
        run: npm ci --ignore-scripts --no-audit --no-fund || true

      - name: Build Repo Slide
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
          GH_USER: statikfintechllc
          # Specify exact repos (owner/name) for the repo slide
          REPOS: "statikfintechllc/GremlinGPT,statikfintechllc/Gremlin-ShadTail-Trader,statikfintechllc/statik-server,statikfintechllc/AscendDocs-of-GovSeverance,statikfintechllc/dragon-boot,statikfintechllc/Gremlin-MCP-Scrap"
          REPO_PAGE_SEC: "6"
        working-directory: docs/r.svg
        run: node scripts/generate-repo-slide.mjs

      - name: Commit if changed
        run: |
          git config --global user.name "gremlin-bot"
          git config --global user.email "actions@github.com"
          git add docs/r.svg/
          git diff --cached --quiet || git commit -m "chore(repos): refresh animated repo slide"
          git pull --rebase
          git push

